export const allTags = [
  "Array",
  "Hash Table",
  "Matrix",
  "Dynamic Programming",
  "Two Pointers",
  "Divide and Conquer",
  "Sorting",
  "Math",
  "Binary Search",
  "Bit Manipulation",
  "Recursion",
  "Counting",
  "Combinatorics",
  "Binary Indexed Tree",
  "Segment Tree",
  "Merge Sort",
  "Ordered Set",
  "Union Find",
  "Hash",
  "Data Structure",
  "Hashing",
  "String",
  "Sliding Window",
  "Linked List",
  "Stack",
  "Monotonic Stack",
  "Geedy",
  "Algorithms",
  "Greedy",
  "Data Structures",
  "Backtracking",
  "Trees",
  "Heap",
  "Heap (Priority Queue)",
  "Quickselect",
  "Heaps And Maps",
  "Design",
  "Data Stream",
  "Bucket Sort",
  "Stacks & Queues",
  "Queue",
  "Stacks And Queues",
  "Doubly-Linked List",
  "Monotonic Queue",
  "Breadth-First Search",
  "Graph",
  "String Matching",
  "Tree",
  "Depth-First Search",
  "Binary Tree",
  "TreeData",
  "Structures",
  "Binary Search Tree",
  "Tree Data Structure",
  "Binary Search Trees",
  "Iterator",
  "DFS",
  "BFS",
  "Topological Sort",
  "Trie",
  "Tries",
  "Strings",
  "Bit Magic",
  "Mathematical",
];

